--- 
abstract: FormValidator::Simple can be handled by plural Catalyst application in mod_perl
author: Ittetsu Miyazaki <ittetsu.miyazaki@gmail.com>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.65
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Plugin-FormValidator-Simple-Messages
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst: 5.30
  Catalyst::Plugin::FormValidator::Simple: 0.12
  YAML: 0
version: 0.01
